config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="news/news_list.html"), name="home"),
                  path(
                      "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path('markdownx/', include('markdownx.urls')),
                  path('comments/', include('django_comments.urls')),
                  # path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("dquora.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  path("news/", include("dquora.news.urls", namespace="news")),
                  path("articles/", include("dquora.articles.urls", namespace="articles")),
                  path("qa/", include("dquora.qa.urls", namespace="qa")),
                  path('messages/', include('dquora.messager.urls', namespace='messages')),
                  path('notifications/', include('dquora.notifications.urls', namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dquora/articles/urls.py
from django.urls import path

from dquora.articles import views

app_name = "articles"
urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("write-new-article/", views.ArticleCreateView.as_view(), name="write_news"),
    path("drafts/", views.DraftListView.as_view(), name="drafts"),
    path("<str:slug>", views.ArticleDetailView.as_view(), name="article"),
    path("edit/<int:pk>", views.ArticleEditView.as_view(), name='edit_article'),

]

dquora/news/urls.py
from django.urls import path

from dquora.news import views

app_name = "news"
urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path('post-news/', views.post_new, name='post-news'),
    path('delete/<str:pk>/', views.NewsDeleteView.as_view(), name='delete_news'),
    path('like/', views.like, name='like_post'),
    path('get-thread/', views.get_thread, name='get_thread'),
    path('post-comment/', views.post_comment, name='post_comments'),
    # 点赞或评论后，WS传回数据，触发AJAX请求，获取更新点赞数与评论数
    path('update-interactions/', views.update_interactions, name='update_interactions'),

]

dquora/qa/urls.py
from django.urls import path

from dquora.qa import views

app_name = "qa"
urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name='unanswered_q'),
    path('answered/', views.AnsweredQuestionListView.as_view(), name='answered_q'),
    path("indexed/", views.QuestionListView.as_view(), name="all_q"),
    path("ask-question/", views.QuestionCreateView.as_view(), name="ask_question"),
    path("question-deatil/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("propose-answer/<int:question_id>/", views.AnswerCreateView.as_view(), name="propose_answer"),
    path("question/vote/", views.question_vote, name='question_vote'),
    path("answer/vote/", views.answer_vote, name='answer_vote'),
    path("accept-answer/", views.accept_answer, name='accept_answer'),

]

dquora/users/urls.py
from django.urls import path

from dquora.users import views

app_name = "users"
urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

dquora/articles/views.py
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django_comments.signals import comment_was_posted

from dquora.articles.models import Article
from dquora.articles.forms import ArticleForm
from dquora.helpers import AuthorRequiredMixin
from dquora.notifications.views import notification_handler


# Create your views here.


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 10
    context_object_name = 'articles'
    template_name = 'articles/article_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data()
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self):
        return Article.objects.get_published()


class DraftListView(ArticleListView):
    """草稿箱文章列表"""

    def get_queryset(self):
        """当前用户的草稿"""
        return Article.objects.filter(user=self.request.user).get_drafts()


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """发表文章"""
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_create.html'
    message = '您的文章已创建成功！'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'articles/article_detail.html'


class ArticleEditView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """编辑文章"""
    model = Article
    form_class = ArticleForm
    message = '您的文章编辑成功！'
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


def notify_comment(**kwargs):
    """文章新增评论时通知作者"""
    actor = kwargs['request'].user  # kwargs['request']提交的HttpRequest
    # kwargs['comment']提交的Comment实例，kwargs['comment'].content_boject 表示Comment关联的通用外键模型类名（即文章对象）
    obj = kwargs['comment'].content_boject
    # 通知文章作者，有新评论了
    notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)  # 使用信号量

dquora/messager/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from dquora.helpers import ajax_required
from dquora.messager.models import Message


class MessagesListView(LoginRequiredMixin, ListView):
    """私信列表页"""
    model = Message
    template_name = 'messager/message_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MessagesListView, self).get_context_data()
        # 获取除当前登录用户外的所有用户，按最近登录时间降序排列
        # get_user_model()获取用户模型，is_active=True当前激活的用户
        context['users_list'] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user).order_by('-last_login')[:10]
        # 最近一次私信互动的用户
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(self.request.user, active_user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        # url.py中设置的username参数，表示指定的用户
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        # 获取URL中username参数指定的用户
        active_user = get_object_or_404(get_user_model(),
                                        username=self.kwargs["username"])
        return Message.objects.get_conversation(self.request.user, active_user)


@login_required
@ajax_required
@require_http_methods(['POST'])
def send_message(request):
    """发送消息，AJAX POST 请求"""
    sender = request.user
    recipient_user_name = request.POST['to']
    recipient = get_user_model().objects.get(username=recipient_user_name)
    message = request.POST['message']
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(sender=sender, recipient=recipient, message=message)
        channel_layer = get_channel_layer()  # 获得频道层
        # 数据字典
        payload = {
            'type': 'receive',  # 固定写法，表示使用consumer.py的receive方法
            # 下面为传递的消息数据
            'message': render_to_string('messager/single_message.html', {'message': msg}),
            'sender': sender.username
        }
        # consumer中异步函数变为同步
        # 在频道层内，使用group_send(group所在组-接收者的username, message消息内容)往recipient_user_name组内发送数据payload
        async_to_sync(channel_layer.group_send)(recipient_user_name, payload)
        return render(request, 'messager/single_message.html', {'message': msg})
    return HttpResponse()


@login_required
@ajax_required
@require_http_methods(['GET'])
def receive_message(request):
    """接收消息， AJAX GET 请求"""
    message_id = request.GET['message_id']
    msg = Message.objects.get(pk=message_id)
    return render(request, 'messager/single_message.html', {'message': msg})

dquora/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DeleteView
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy

from dquora.news.models import News
from dquora.helpers import ajax_required, AuthorRequiredMixin


# Create your views here.


class NewsListView(LoginRequiredMixin, ListView):
    """首页动态"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self):
        return News.objects.filter(reply=False)


class NewsDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_new(request):
    """发送动态， AJAX POST 请求"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        # 先渲染为html模板，然后返回给前端
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞， AJAX POST 提交"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    user = request.user
    news.switch_like(user)
    return JsonResponse({'likes': news.count_likers()})


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_thread(request):
    """返回动态的评论， AJAX GET 请求"""
    news_id = request.GET['news']
    news = News.objects.get(pk=news_id)
    # 没有评论时显示该动态
    news_html = render_to_string('news/news_single.html', {'news': news})
    # 有评论时，返回该动态下所有评论
    thread_html = render_to_string('news/news_thread.html', {'thread': news.get_thread()})
    return JsonResponse({
        'uuid': news_id,
        'news': news_html,
        'thread': thread_html
    })


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_comment(request):
    """提交评论， AJAX POST 请求"""
    text = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    # 获取该条动态
    parent = News.objects.get(pk=parent_id)
    if text:
        parent.reply_this(request.user, text)
        return JsonResponse({'comments': parent.comment_count()})
    else:
        return HttpResponseBadRequest('内容不能为空！')


@login_required
@ajax_required
@require_http_methods(['POST'])
def update_interactions(request):
    """点赞或评论的动作交互 引起的"""
    news_id = request.POST['id_value']
    news = News.objects.get(pk=news_id)
    return JsonResponse({'likes': news.count_likers(), 'comments': news.comment_count()})

dquora/notifications/views.py
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from asgiref.sync import async_to_sync

from channels.layers import get_channel_layer

from dquora.notifications.models import Notification


# Create your views here.

class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """未读通知列表"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def get_latest_notifications(request):
    """最近的未读通知"""
    notifications = request.user.notifications.get_most_recent()
    return render(request, 'notifications/most_recent.html', {'notifications': notifications})


@login_required
def mark_all_as_read(request):
    """将所有通知标为已读"""
    request.user.notifications.mark_all_as_read()
    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'用户{request.user.username}的所有通知标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug):
    """根据slug标为已读"""
    notification = get_object_or_404(Notification, slug=slug)
    notification.mark_as_read()

    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'通知{notification}标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


def notification_handler(actor, recipient, verb, action_object, **kwargs):
    """
    通知处理器
    :param actor:           request.user对象
    :param recipient:       User instance接收者
    :param verb:            str 通知类型
    :param action_object:   Instance动作对象
    :param kwargs:          key，id_value等
    :return:                None
    """
    if actor.username == action_object.user.username and actor.username != recipient.username:
        # 只通知接收者，即recipient == 动作对象的作者
        key = kwargs.get('key', 'notification')
        id_value = kwargs.get('id_value', None)
        Notification.objects.create(
            actor=actor,
            recipient=recipient,
            verb=verb,
            action_object=action_object
        )
        # WS: 传递给consumer的receive()方法
        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            # 传给receive()的数据
            'key': key,  # 前端收到该参数后的再次触发AJAX请求
            'id_value': id_value,
            'actor_name': actor.username
        }
        async_to_sync(channel_layer.group_send)('notifications', payload)

dquora/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, UpdateView
from django.urls import reverse

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    template_name = "users/user_detail.html"
    # model里包含slug的字段，通常是username
    slug_field = "username"
    # url中包含slug（username）的key-value关键字参数
    slug_url_kwarg = "username"


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    template_name = "users/user_form.html"
    fields = ["nickname","job_title","introduction","picture","location","personal_url","weibo","zhihu","github","linkedin"]
    success_message = _("Information successfully updated")

    # 更新成功后调整的页面
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    # 获取需要返回给前端的对象，返回当前登录用户的数据
    def get_object(self):
        return self.request.user

dquora/templates/articles/article_create.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}写文章{% endblock %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">文章</a></li>
            <li class="breadcrumb-item active" aria-current="page">写文章</li>
        </ol>
    </nav>
    <form action="{% url 'articles:write_news' %}" enctype="multipart/form-data" id="article-form" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="button" class="btn btn-primary publish">发表</button>
            <button type="button" class="btn btn-success draft">保存草稿</button>
            <a href="{% url 'articles:list' %}" class="btn btn-light" style="float: right">取消</a>
        </div>
    </form>
    {{ form.media }}
{% endblock %}
{% block js %}
    <script src="{% static 'js/articles.js' %}"></script>
{% endblock %}

dquora/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load static thumbnail comments %}

{% block title %}{{ article.title|title }}{% endblock %}

{% block content %}
      <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
                <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">文章</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ article.title|title }}</li>
            </ol>
        </nav>
        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <h2 class="text-center">{{ article.title|title }}</h2>
                <!-- Author -->
                <p class="text-left">
                    <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
                    发表于{{ article.created_at }}
                </p>
                <hr>
                <!-- 文章图片 -->
                {% thumbnail article.image "1920x1080" as im %}
                    <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
                    {% empty %}
                    <img class="img-fluid rounded" src="http://placehold.it/1920x1080" alt="Card Image">
                {% endthumbnail %}
                <hr>
                <!-- Post Content -->
                <p class="card-text">{{ article.get_markdown|safe }}</p>
                <hr>
                <!-- Comments Form 提交评论表单-->
                <div class="card my-4">
                    <h5 class="card-header">评论</h5>
                    <div class="card-body">
                        {% if user.is_authenticated %}
                            {% get_comment_form for article as form %}
                            <form action="{% comment_form_target %}" method="POST">
                                {% csrf_token %}
                                {% comment %}这个textarea标签显示，其余input标签都自动隐藏了，提交时其余信息自动保存了{% endcomment %}
                                <div id="id_comment" class="form-group">
                                    <textarea name="comment" rows="5" maxlength="400" class="textarea form-control"></textarea>
                                </div>
                                {{ form.content_type }}
                                {{ form.object_pk }}
                                {{ form.timestamp }}
                                {{ form.security_hash }}
                                <input type="hidden" name="next" value="{% url 'articles:article' article.slug %}"/>
                                <input class="btn btn-info" type="submit" value="提交" id="id_submit"/>
                            </form>
                        {% endif %}
                    </div>
                </div>

                <!-- Single Comment 显示评论列表-->
                {% get_comment_list for article as comment_list %}
                {% for comment in comment_list %}
                    <div class="media mb-4">
                        {% thumbnail comment.user.picture "x50" as im %}
                            <img class="d-flex mr-3 rounded-circle" src="{{ im.url }}" alt="用户头像" id="pic"/>
                            {% empty %}
                            <img class="d-flex mr-3 rounded-circle" src="{% static 'img/user.png' %}" height="50px" alt="没有头像"/>
                        {% endthumbnail %}
                        <div class="media-body">
                            <h5 class="mt-0">{{ comment.user.get_profile_name }}</h5>
                            {{ comment }}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Write Article Widget -->
                {% if request.user.is_authenticated %}
                    <div class="card my-4">
                        <div class="card-body text-center">
                            <a class="btn btn-success" href="{% url 'articles:write_news' %}" title="写文章">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 写文章</a>

                            {% if request.user.username == article.user.username %}
                                <a class="btn btn-primary" href="{% url 'articles:edit_article' article.pk %}" title="编辑文章">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</a>
                            {% endif %}

                        </div>
                    </div>
                {% endif %}
                <!-- 云标签 -->
                <div class="card my-4">
                    <h5 class="card-header">云标签</h5>
                    <div class="card-body">
                        {% for tag in article.tags.all %}
                            <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

dquora/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static thumbnail %}

{% block title %}文章{% endblock %}
{% block content %}
{#    Page Content#}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'articles:list' %}">文章</a></li>
            </ol>
        </nav>

        <div class="row">
{#            Blog Entries Column#}
            <div class="col-md-8">
                {% for article in articles %}
{#                   blog Post#}
                    <div class="card mb-4">
                        {% thumbnail article.image "1920x1080" as im %}
                        <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
                        {% empty %}
                            <img src="http://placehold.it/1920x1080" alt="图片大小" class="card-img-top">
                        {% endthumbnail %}

                        <div class="card-body">
                            <h3 class="card-title">{{ article.title|title }}</h3>
                            <p class="">{{ article.get_markdown|safe|truncatechars:100 }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
                            发表于{{ article.created_at }}
                            {% for tag in article.tags.names %}
                                <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
                            {% endfor %}
                            <a style="float:right" href="{% url 'articles:article' article.slug %}" class="btn-sm btn-primary">阅读全文→</a>
                        </div>
                    </div>
                    {% empty %}
                    <h4 class="no-data"><a href="{% url 'articles:write_news' %}">快来成为第一个写文章的吧！</a></h4>
                {% endfor %}
            </div>
            {% include 'pagination.html' %}
{#            Sidebar Widgets Column#}
            <div class="col-md-4">
                {% if request.user.is_authenticated %}
                    <div class="card my-4">
                        <div class="card-body text-center">
                            <a class="btn btn-success" href="{% url 'articles:write_news' %}" title="写文章">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 写文章</a>
                            <a class="btn btn-primary" href="{% url 'articles:drafts' %}" title="草稿箱">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 草稿箱</a>
                        </div>
                    </div>
                {% endif %}
                {% comment %}云标签{% endcomment %}
                <div class="card my-4">
                    <h5 class="card-header">云标签</h5>
                    <div class="card-body">
                        {% for tag, count in popular_tags %}
                             <a href="#"><span class="badge badge-info">{{ tag }}({{ count }})</span></a>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

dquora/templates/articles/article_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}更新文章 - {{ block.super }}{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'articles:drafts' %}">草稿箱</a></li>
            <li class="breadcrumb-item active" aria-current="page">更新文章</li>
        </ol>
    </nav>
    <form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data" id="article-form" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="button" class="btn btn-primary update">更新</button>
            <button type="button" class="btn btn-default draft">保存草稿</button>
            <a href="{% url 'articles:drafts' %}" class="btn btn-default">取消</a>
        </div>
    </form>
    {{ form.media }}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/articles.js' %}"></script>
{% endblock js %}