config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="news/news_list.html"), name="home"),
                  path(
                      "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path('markdownx/', include('markdownx.urls')),
                  path('comments/', include('django_comments.urls')),
                  # path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("dquora.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  path("news/", include("dquora.news.urls", namespace="news")),
                  path("articles/", include("dquora.articles.urls", namespace="articles")),
                  path("qa/", include("dquora.qa.urls", namespace="qa")),
                  path('messages/', include('dquora.messager.urls', namespace='messages')),
                  path('notifications/', include('dquora.notifications.urls', namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dquora/messager/urls.py
from django.urls import path

from dquora.messager import views

app_name = "messager"
urlpatterns = [
    path('', views.MessagesListView.as_view(), name='messages_list'),
    path('send-message/', views.send_message, name='send_message'),
    path('receive_message/', views.receive_message, name='receive_message'),
    path('<username>/', views.ConversationListView.as_view(), name='conversation_detail'),



]

dquora/news/urls.py
from django.urls import path

from dquora.news import views

app_name = "news"
urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path('post-news/', views.post_new, name='post-news'),
    path('delete/<str:pk>/', views.NewsDeleteView.as_view(), name='delete_news'),
    path('like/', views.like, name='like_post'),
    path('get-thread/', views.get_thread, name='get_thread'),
    path('post-comment/', views.post_comment, name='post_comments'),
    # 点赞或评论后，WS传回数据，触发AJAX请求，获取更新点赞数与评论数
    path('update-interactions/', views.update_interactions, name='update_interactions'),

]

dquora/notifications/urls.py
from django.urls import path

from dquora.notifications import views

app_name = "notifications"
urlpatterns = [
    path("", views.NotificationUnreadListView.as_view(), name="unread"),
    path('mark-as-read/<str:slug>/', views.mark_as_read, name='mark_as_read'),
    path('mark-all-as-read/', views.mark_all_as_read, name='mark_all_read'),
    path('latest-notifications/', views.get_latest_notifications, name='latest_notifications'),

]

dquora/qa/urls.py
from django.urls import path

from dquora.qa import views

app_name = "qa"
urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name='unanswered_q'),
    path('answered/', views.AnsweredQuestionListView.as_view(), name='answered_q'),
    path("indexed/", views.QuestionListView.as_view(), name="all_q"),
    path("ask-question/", views.QuestionCreateView.as_view(), name="ask_question"),
    path("question-deatil/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("propose-answer/<int:question_id>/", views.AnswerCreateView.as_view(), name="propose_answer"),
    path("question/vote/", views.question_vote, name='question_vote'),
    path("answer/vote/", views.answer_vote, name='answer_vote'),
    path("accept-answer/", views.accept_answer, name='accept_answer'),

]

dquora/users/urls.py
from django.urls import path

from dquora.users import views

app_name = "users"
urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

dquora/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from dquora.articles.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput)  # 隐藏
    edited = forms.BooleanField(widget=forms.HiddenInput(), required=False, initial=False)  # 隐藏
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'tags', 'status'] # 忘记添加status表单字段了，前端js怎么修改都是默认保存为D草稿！

dquora/qa/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from dquora.qa.models import Question


class QuestionForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput)  # 隐藏显示
    content = MarkdownxFormField()

    class Meta:
        model = Question
        fields = ['title', 'status', 'content', 'tags']

dquora/articles/views.py
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django_comments.signals import comment_was_posted

from dquora.articles.models import Article
from dquora.articles.forms import ArticleForm
from dquora.helpers import AuthorRequiredMixin
from dquora.notifications.views import notification_handler


# Create your views here.


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 10
    context_object_name = 'articles'
    template_name = 'articles/article_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data()
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self):
        return Article.objects.get_published()


class DraftListView(ArticleListView):
    """草稿箱文章列表"""

    def get_queryset(self):
        """当前用户的草稿"""
        return Article.objects.filter(user=self.request.user).get_drafts()


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """发表文章"""
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_create.html'
    message = '您的文章已创建成功！'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'articles/article_detail.html'


class ArticleEditView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """编辑文章"""
    model = Article
    form_class = ArticleForm
    message = '您的文章编辑成功！'
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


def notify_comment(**kwargs):
    """文章新增评论时通知作者"""
    actor = kwargs['request'].user  # kwargs['request']提交的HttpRequest
    # kwargs['comment']提交的Comment实例，kwargs['comment'].content_boject 表示Comment关联的通用外键模型类名（即文章对象）
    obj = kwargs['comment'].content_boject
    # 通知文章作者，有新评论了
    notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)  # 使用信号量

dquora/messager/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from dquora.helpers import ajax_required
from dquora.messager.models import Message


class MessagesListView(LoginRequiredMixin, ListView):
    """私信列表页"""
    model = Message
    template_name = 'messager/message_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MessagesListView, self).get_context_data()
        # 获取除当前登录用户外的所有用户，按最近登录时间降序排列
        # get_user_model()获取用户模型，is_active=True当前激活的用户
        context['users_list'] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user).order_by('-last_login')[:10]
        # 最近一次私信互动的用户
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(self.request.user, active_user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        # url.py中设置的username参数，表示指定的用户
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        # 获取URL中username参数指定的用户
        active_user = get_object_or_404(get_user_model(),
                                        username=self.kwargs["username"])
        return Message.objects.get_conversation(self.request.user, active_user)


@login_required
@ajax_required
@require_http_methods(['POST'])
def send_message(request):
    """发送消息，AJAX POST 请求"""
    sender = request.user
    recipient_user_name = request.POST['to']
    recipient = get_user_model().objects.get(username=recipient_user_name)
    message = request.POST['message']
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(sender=sender, recipient=recipient, message=message)
        channel_layer = get_channel_layer()  # 获得频道层
        # 数据字典
        payload = {
            'type': 'receive',  # 固定写法，表示使用consumer.py的receive方法
            # 下面为传递的消息数据
            'message': render_to_string('messager/single_message.html', {'message': msg}),
            'sender': sender.username
        }
        # consumer中异步函数变为同步
        # 在频道层内，使用group_send(group所在组-接收者的username, message消息内容)往recipient_user_name组内发送数据payload
        async_to_sync(channel_layer.group_send)(recipient_user_name, payload)
        return render(request, 'messager/single_message.html', {'message': msg})
    return HttpResponse()


@login_required
@ajax_required
@require_http_methods(['GET'])
def receive_message(request):
    """接收消息， AJAX GET 请求"""
    message_id = request.GET['message_id']
    msg = Message.objects.get(pk=message_id)
    return render(request, 'messager/single_message.html', {'message': msg})

dquora/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DeleteView
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy

from dquora.news.models import News
from dquora.helpers import ajax_required, AuthorRequiredMixin


# Create your views here.


class NewsListView(LoginRequiredMixin, ListView):
    """首页动态"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self):
        return News.objects.filter(reply=False)


class NewsDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_new(request):
    """发送动态， AJAX POST 请求"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        # 先渲染为html模板，然后返回给前端
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞， AJAX POST 提交"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    user = request.user
    news.switch_like(user)
    return JsonResponse({'likes': news.count_likers()})


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_thread(request):
    """返回动态的评论， AJAX GET 请求"""
    news_id = request.GET['news']
    news = News.objects.get(pk=news_id)
    # 没有评论时显示该动态
    news_html = render_to_string('news/news_single.html', {'news': news})
    # 有评论时，返回该动态下所有评论
    thread_html = render_to_string('news/news_thread.html', {'thread': news.get_thread()})
    return JsonResponse({
        'uuid': news_id,
        'news': news_html,
        'thread': thread_html
    })


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_comment(request):
    """提交评论， AJAX POST 请求"""
    text = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    # 获取该条动态
    parent = News.objects.get(pk=parent_id)
    if text:
        parent.reply_this(request.user, text)
        return JsonResponse({'comments': parent.comment_count()})
    else:
        return HttpResponseBadRequest('内容不能为空！')


@login_required
@ajax_required
@require_http_methods(['POST'])
def update_interactions(request):
    """点赞或评论的动作交互 引起的"""
    news_id = request.POST['id_value']
    news = News.objects.get(pk=news_id)
    return JsonResponse({'likes': news.count_likers(), 'comments': news.comment_count()})

dquora/notifications/views.py
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from asgiref.sync import async_to_sync

from channels.layers import get_channel_layer

from dquora.notifications.models import Notification


# Create your views here.

class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """未读通知列表"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def get_latest_notifications(request):
    """最近的未读通知"""
    notifications = request.user.notifications.get_most_recent()
    return render(request, 'notifications/most_recent.html', {'notifications': notifications})


@login_required
def mark_all_as_read(request):
    """将所有通知标为已读"""
    request.user.notifications.mark_all_as_read()
    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'用户{request.user.username}的所有通知标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug):
    """根据slug标为已读"""
    notification = get_object_or_404(Notification, slug=slug)
    notification.mark_as_read()

    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'通知{notification}标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


def notification_handler(actor, recipient, verb, action_object, **kwargs):
    """
    通知处理器
    :param actor:           request.user对象
    :param recipient:       User instance接收者
    :param verb:            str 通知类型
    :param action_object:   Instance动作对象
    :param kwargs:          key，id_value等
    :return:                None
    """
    if actor.username == action_object.user.username and actor.username != recipient.username:
        # 只通知接收者，即recipient == 动作对象的作者
        key = kwargs.get('key', 'notification')
        id_value = kwargs.get('id_value', None)
        Notification.objects.create(
            actor=actor,
            recipient=recipient,
            verb=verb,
            action_object=action_object
        )
        # WS: 传递给consumer的receive()方法
        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            # 传给receive()的数据
            'key': key,  # 前端收到该参数后的再次触发AJAX请求
            'id_value': id_value,
            'actor_name': actor.username
        }
        async_to_sync(channel_layer.group_send)('notifications', payload)

dquora/templates/base.html
{% load static thumbnail compress cache %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} -Dquora</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta name="description" content="Dquora问答社区">
    <meta name="author" content="__Jack__">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% compress css %}
        <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Your stuff: Third-party CSS libraries go here -->
        <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <!-- This file stores project-specific CSS -->
        <link rel="stylesheet" href="{% static 'css/dquora.css' %}">
        {% block css %}{% endblock css %}
    {% endcompress %}

</head>
<body>

{% cache 3600 sidebar request.user.username %}
    <nav class="navbar fixed-top navbar-expand-sm bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'news:list' %}">赞 乎&nbsp;&nbsp;</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn-sm" href="{% url 'notifications:latest_notifications' %}" id="notifications" data-toggle="popover"
                           data-title="通知">
                            <i class="fa fa-bell-o" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>&nbsp;&nbsp;

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'news:list' %}">&nbsp;&nbsp;首页</a></li>&nbsp;&nbsp;
                    <li class="nav-item"><a class="nav-link" href="{% url 'articles:list' %}">文章</a></li>&nbsp;&nbsp;
                    <li class="nav-item"><a class="nav-link" href="{% url 'qa:all_q' %}">问答</a></li>&nbsp;&nbsp;
                    <li class="nav-item"><a class="nav-link" href="{% url 'messager:messages_list' %}">私信</a></li>&nbsp;&nbsp;
                </ul>


                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                {% thumbnail request.user.picture "x40" as im %}
                                    <img src="{{ im.url }}" style="border-radius: 50%;" alt="用户头像" class="user-image">
                                    {% empty %}
                                    <img src="{% static 'img/user.png' %}" height="40px" alt="没有头像"/>
                                {% endthumbnail %}
                                {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">
                                    <i class="fa fa-cogs fa-fw" aria-hidden="true"></i> 设置</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">
                                    <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> 退出</a>
                            </div>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
{% endcache %}

<div class="mb-3"></div>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div id="messages" class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock content %}
</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- Required by Bootstrap v4 -->
{% compress js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
    <!-- place project specific Javascript in this file -->
    <script type="text/javascript">
        const currentUser = "{{ request.user.username }}";
    </script>
    <script src="{% static 'js/reconnecting-websocket.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/notifications.js' %}" type="text/javascript"></script>
    {% block js %}{% endblock js %}
{% endcompress %}

</body>

<!-- /.container -->
</html>

dquora/templates/base1.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}zhanhu{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="a Q&A website">
    <meta name="author" content="__jack__">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->{% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">{% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->{% compress js %}
      <script defer src="{% static 'js/project.js' %}"></script>{% endcompress %}

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">zhanhu</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

dquora/templates/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>