config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="news/news_list.html"), name="home"),
                  path(
                      "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path('markdownx/', include('markdownx.urls')),
                  path('comments/', include('django_comments.urls')),
                  # path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("dquora.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  path("news/", include("dquora.news.urls", namespace="news")),
                  path("articles/", include("dquora.articles.urls", namespace="articles")),
                  path("qa/", include("dquora.qa.urls", namespace="qa")),
                  path('messages/', include('dquora.messager.urls', namespace='messages')),
                  path('notifications/', include('dquora.notifications.urls', namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dquora/news/urls.py
from django.urls import path

from dquora.news import views

app_name = "news"
urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path('post-news/', views.post_new, name='post-news'),
    path('delete/<str:pk>/', views.NewsDeleteView.as_view(), name='delete_news'),
    path('like/', views.like, name='like_post'),
    path('get-thread/', views.get_thread, name='get_thread'),
    path('post-comment/', views.post_comment, name='post_comments'),
    # 点赞或评论后，WS传回数据，触发AJAX请求，获取更新点赞数与评论数
    path('update-interactions/', views.update_interactions, name='update_interactions'),

]

dquora/qa/urls.py
from django.urls import path

from dquora.qa import views

app_name = "qa"
urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name='unanswered_q'),
    path('answered/', views.AnsweredQuestionListView.as_view(), name='answered_q'),
    path("indexed/", views.QuestionListView.as_view(), name="all_q"),
    path("ask-question/", views.QuestionCreateView.as_view(), name="ask_question"),
    path("question-deatil/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("propose-answer/<int:question_id>/", views.AnswerCreateView.as_view(), name="propose_answer"),
    path("question/vote/", views.question_vote, name='question_vote'),
    path("answer/vote/", views.answer_vote, name='answer_vote'),
    path("accept-answer/", views.accept_answer, name='accept_answer'),

]

dquora/users/urls.py
from django.urls import path

from dquora.users import views

app_name = "users"
urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

dquora/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from dquora.articles.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput)  # 隐藏
    edited = forms.BooleanField(widget=forms.HiddenInput(), required=False, initial=False)  # 隐藏
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'tags', 'status'] # 忘记添加status表单字段了，前端js怎么修改都是默认保存为D草稿！

dquora/articles/views.py
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django_comments.signals import comment_was_posted

from dquora.articles.models import Article
from dquora.articles.forms import ArticleForm
from dquora.helpers import AuthorRequiredMixin
from dquora.notifications.views import notification_handler


# Create your views here.


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 10
    context_object_name = 'articles'
    template_name = 'articles/article_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data()
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self):
        return Article.objects.get_published()


class DraftListView(ArticleListView):
    """草稿箱文章列表"""

    def get_queryset(self):
        """当前用户的草稿"""
        return Article.objects.filter(user=self.request.user).get_drafts()


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """发表文章"""
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_create.html'
    message = '您的文章已创建成功！'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'articles/article_detail.html'


class ArticleEditView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """编辑文章"""
    model = Article
    form_class = ArticleForm
    message = '您的文章编辑成功！'
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleEditView, self).form_valid(form)

    # 创建成功后跳转
    def get_success_url(self):
        # 将消息传递给下一次请求
        messages.success(self.request, self.message)
        return reverse_lazy('articles:list')


def notify_comment(**kwargs):
    """文章新增评论时通知作者"""
    actor = kwargs['request'].user  # kwargs['request']提交的HttpRequest
    # kwargs['comment']提交的Comment实例，kwargs['comment'].content_boject 表示Comment关联的通用外键模型类名（即文章对象）
    obj = kwargs['comment'].content_boject
    # 通知文章作者，有新评论了
    notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)  # 使用信号量

dquora/messager/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from dquora.helpers import ajax_required
from dquora.messager.models import Message


class MessagesListView(LoginRequiredMixin, ListView):
    """私信列表页"""
    model = Message
    template_name = 'messager/message_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MessagesListView, self).get_context_data()
        # 获取除当前登录用户外的所有用户，按最近登录时间降序排列
        # get_user_model()获取用户模型，is_active=True当前激活的用户
        context['users_list'] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user).order_by('-last_login')[:10]
        # 最近一次私信互动的用户
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(self.request.user, active_user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        # url.py中设置的username参数，表示指定的用户
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        # 获取URL中username参数指定的用户
        active_user = get_object_or_404(get_user_model(),
                                        username=self.kwargs["username"])
        return Message.objects.get_conversation(self.request.user, active_user)


@login_required
@ajax_required
@require_http_methods(['POST'])
def send_message(request):
    """发送消息，AJAX POST 请求"""
    sender = request.user
    recipient_user_name = request.POST['to']
    recipient = get_user_model().objects.get(username=recipient_user_name)
    message = request.POST['message']
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(sender=sender, recipient=recipient, message=message)
        channel_layer = get_channel_layer()  # 获得频道层
        # 数据字典
        payload = {
            'type': 'receive',  # 固定写法，表示使用consumer.py的receive方法
            # 下面为传递的消息数据
            'message': render_to_string('messager/single_message.html', {'message': msg}),
            'sender': sender.username
        }
        # consumer中异步函数变为同步
        # 在频道层内，使用group_send(group所在组-接收者的username, message消息内容)往recipient_user_name组内发送数据payload
        async_to_sync(channel_layer.group_send)(recipient_user_name, payload)
        return render(request, 'messager/single_message.html', {'message': msg})
    return HttpResponse()


@login_required
@ajax_required
@require_http_methods(['GET'])
def receive_message(request):
    """接收消息， AJAX GET 请求"""
    message_id = request.GET['message_id']
    msg = Message.objects.get(pk=message_id)
    return render(request, 'messager/single_message.html', {'message': msg})

dquora/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DeleteView
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy

from dquora.news.models import News
from dquora.helpers import ajax_required, AuthorRequiredMixin


# Create your views here.


class NewsListView(LoginRequiredMixin, ListView):
    """首页动态"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self):
        return News.objects.filter(reply=False)


class NewsDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_new(request):
    """发送动态， AJAX POST 请求"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        # 先渲染为html模板，然后返回给前端
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞， AJAX POST 提交"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    user = request.user
    news.switch_like(user)
    return JsonResponse({'likes': news.count_likers()})


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_thread(request):
    """返回动态的评论， AJAX GET 请求"""
    news_id = request.GET['news']
    news = News.objects.get(pk=news_id)
    # 没有评论时显示该动态
    news_html = render_to_string('news/news_single.html', {'news': news})
    # 有评论时，返回该动态下所有评论
    thread_html = render_to_string('news/news_thread.html', {'thread': news.get_thread()})
    return JsonResponse({
        'uuid': news_id,
        'news': news_html,
        'thread': thread_html
    })


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_comment(request):
    """提交评论， AJAX POST 请求"""
    text = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    # 获取该条动态
    parent = News.objects.get(pk=parent_id)
    if text:
        parent.reply_this(request.user, text)
        return JsonResponse({'comments': parent.comment_count()})
    else:
        return HttpResponseBadRequest('内容不能为空！')


@login_required
@ajax_required
@require_http_methods(['POST'])
def update_interactions(request):
    """点赞或评论的动作交互 引起的"""
    news_id = request.POST['id_value']
    news = News.objects.get(pk=news_id)
    return JsonResponse({'likes': news.count_likers(), 'comments': news.comment_count()})

dquora/notifications/views.py
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from asgiref.sync import async_to_sync

from channels.layers import get_channel_layer

from dquora.notifications.models import Notification


# Create your views here.

class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """未读通知列表"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def get_latest_notifications(request):
    """最近的未读通知"""
    notifications = request.user.notifications.get_most_recent()
    return render(request, 'notifications/most_recent.html', {'notifications': notifications})


@login_required
def mark_all_as_read(request):
    """将所有通知标为已读"""
    request.user.notifications.mark_all_as_read()
    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'用户{request.user.username}的所有通知标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug):
    """根据slug标为已读"""
    notification = get_object_or_404(Notification, slug=slug)
    notification.mark_as_read()

    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'通知{notification}标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


def notification_handler(actor, recipient, verb, action_object, **kwargs):
    """
    通知处理器
    :param actor:           request.user对象
    :param recipient:       User instance接收者
    :param verb:            str 通知类型
    :param action_object:   Instance动作对象
    :param kwargs:          key，id_value等
    :return:                None
    """
    if actor.username == action_object.user.username and actor.username != recipient.username:
        # 只通知接收者，即recipient == 动作对象的作者
        key = kwargs.get('key', 'notification')
        id_value = kwargs.get('id_value', None)
        Notification.objects.create(
            actor=actor,
            recipient=recipient,
            verb=verb,
            action_object=action_object
        )
        # WS: 传递给consumer的receive()方法
        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            # 传给receive()的数据
            'key': key,  # 前端收到该参数后的再次触发AJAX请求
            'id_value': id_value,
            'actor_name': actor.username
        }
        async_to_sync(channel_layer.group_send)('notifications', payload)

dquora/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, UpdateView
from django.urls import reverse

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    template_name = "users/user_detail.html"
    # model里包含slug的字段，通常是username
    slug_field = "username"
    # url中包含slug（username）的key-value关键字参数
    slug_url_kwarg = "username"


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    template_name = "users/user_form.html"
    fields = ["nickname","job_title","introduction","picture","location","personal_url","weibo","zhihu","github","linkedin"]
    success_message = _("Information successfully updated")

    # 更新成功后调整的页面
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    # 获取需要返回给前端的对象，返回当前登录用户的数据
    def get_object(self):
        return self.request.user

dquora/templates/news/news_confirm_delete.html
{% extends "base.html" %}
{#{% block head_title %}删除动态{% endblock %}#}
{% block content %}
    <h3>确定要删除吗?</h3>

    <form action="{% url 'news:delete_news' news.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">删除</button>
    </form>

{% endblock %}

dquora/templates/news/news_form_modal.html
<div class="modal fade" id="newsFormModal" tabindex="-1" role="dialog" aria-labelledby="newsFormModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">说说最近在发生的事</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="postNewsForm" role="form" method="post" action="#" onsubmit="return false">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="newsInput"></label><textarea id="newsInput" name="post" rows="5" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" id="postNews" class="btn btn-primary">
                    <i class="fa fa-paper-plane" aria-hidden="true"></i> 发送
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

dquora/templates/news/news_list.html
{% extends 'base.html' %}
{% load static thumbnail %}
{% block title %}首页动态{{ block.super }}{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/news.css' %}">
{% endblock css %}

{% block content %}
    <!-- Container -->
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-centered">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newsFormModal">
                    <i class="fa fa-share-alt" aria-hidden="true"></i> 发表动态
                </button>
                {% include 'news/news_form_modal.html' %}
                {% include 'news/news_thread_modal.html' %}
                <div class="mb-2"></div>

                <!-- 有新的状态时 -->
                <div class="stream-update">
                    <a href="{% url 'news:list' %}"><span class="new-posts"></span>以下是新的动态</a>
                </div>
                <!-- 有新的状态时 -->

                <div class="infinite-container">
                    <ul class="stream">

                        {% for news in news_list %}
                            {% include 'news/news_single.html' with news=news %}
                        {% endfor %}
                    </ul>
                </div>
                {% include 'pagination.html' %}

            </div>
        </div>
    </div>
    <!-- End container -->

{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.waypoints.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/infinite.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/news.js' %}" type="text/javascript"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.load').show();
            },
            onAfterPageLoad: function ($items) {
                $('.load').hide();
            }
        });
    </script>
{% endblock js %}

dquora/templates/news/news_single.html
{% load static thumbnail %}

<li class="infinite-item card" news-id="{{ news.uuid }}">
    <div class="card-body">
        <div class="profile-picture">
            {% thumbnail news.user.picture "x50" as im %}
                <img src="{{ im.url }}" class="user-image pull-left" style="border-radius: 50%;" alt="用户头像">
            {% empty %}
                <img src="{% static 'img/user.png' %}" class="pull-left" height="50px" alt="没有头像"/>
            {% endthumbnail %}
        </div>

        <div class="post">
            <!--自己发送的动态显示删除按钮-->
            {% if request.user.username == news.user.username %}
                <a href="{% url 'news:delete_news' news.pk %}">
                    <i class="fa fa-times pull-right" aria-hidden="true" title="点击删除这条动态"></i>
                </a>
            {% endif %}
            <p>
                <strong>
{#                    <a href="{% url 'users:detail' news.user.username %}">{{ news.user.get_profile_name }}</a>#}
                </strong>
            </p>
            <p>{{ news }}</p>
        </div>
    </div>
    <div class="interaction" id="interaction">
        <a href="#" class="like" title="{% for i in news.get_likers %}{{ i }}&#10;{% endfor %}">
            {% if request.user in news.get_likers %}
                <i class="heart fa fa-heart" aria-hidden="true"></i>
            {% else %}
                <i class="heart fa fa-heart-o" aria-hidden="true"></i>
            {% endif %}
            <span class="like-count">{{ news.count_likers }}</span>
        </a>
        <a href="#" class="comment"><i class="fa fa-comment-o" aria-hidden="true"></i>
            <span class="comment-count">{{ news.comment_count }}</span>
        </a>
        <span class="timestamp">{{ news.created_at|timesince }}之前</span>
    </div>
</li>

dquora/templates/news/news_thread.html
{% load static thumbnail %}

{% for reply in thread %}
    <li class="card" news-id="{{ reply.uuid_id }}">
        <div class="card-body">
            <div class="profile-picture">
                {% thumbnail reply.user.picture "x50" as im %}
                    <img src="{{ im.url }}" class="user-image pull-left" style="border-radius: 50%;" alt="用户头像">
                {% empty %}
                    <img src="{% static 'img/user.png' %}" class="pull-left" height="50px" alt="没有头像"/>
                {% endthumbnail %}
            </div>
            <div class="post">
                {% if request.user.username == reply.user.username %}
                    <a href="{% url 'news:delete_news' reply.pk %}">
                        <i class="fa fa-times pull-right" aria-hidden="true" title="点击删除这条动态"></i>
                    </a>
                {% endif %}
                <p>
                    <strong>
                        <a href="{% url 'users:detail' reply.user.username %}">{{ reply.user.get_profile_name }}</a>
                    </strong>
                </p>
                <p>{{ reply }}</p>
            </div>
        </div>
        <div class="interaction" id="interaction">
            <a href="#" class="like" title="{% for i in news.get_likers %}{{ i }}&#10;{% endfor %}">
                {% if request.user in news.get_likers %}
                    <i class="heart fa fa-heart" aria-hidden="true"></i>
                {% else %}
                    <i class="heart fa fa-heart-o" aria-hidden="true"></i>
                {% endif %}
                <span class="like-count">{{ news.count_likers }}</span>
            </a>
            <a href="#" class="comment"><i class="fa fa-comment-o" aria-hidden="true"></i>
                <span class="comment-count">{{ news.comment_count }}</span>
            </a>
            <span class="timestamp">{{ reply.created_at|timesince }}之前</span>
        </div>
    </li>
{% endfor %}

dquora/templates/news/news_thread_modal.html
{% load static thumbnail %}

<div class="modal fade" id="newsThreadModal" tabindex="-1" role="dialog" aria-labelledby="newsThreadModalLabel" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content">
            <!-- Body -->
            <div class="modal-body">
                <ul class="stream" id="newsContent"></ul>
                <ul class="stream">
                    <li class="card">
                        <form id="replyNewsForm" role="form" method="post" action="#" onsubmit="return false">
                            {% csrf_token %}
                            <input type="hidden" name="parent" value="">
                            <div class="form-group">
                                <label for="replyInput"></label>
                                <textarea id="replyInput" name="reply" rows="5" class="form-control"></textarea>
                            </div>
                        </form>
                        <div class="card-footer">
                            <button type="button" id="replyNews" class="btn btn-primary pull-right">
                                <i class="fa fa-paper-plane" aria-hidden="true"></i> 回复
                            </button>
                        </div>
                    </li>
                </ul>
                <ul class="stream" id="threadContent"></ul>
            </div>
            <!-- Body -->
        </div>
    </div>
</div>